# [START app_yaml]
env: flex
runtime: nodejs
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)$
    static_files: build/\1
    upload: build/(.*)
manual_scaling:
  instances: 1
resources:
  cpu: .5
  memory_gb: 0.91
  disk_size_gb: 4.9
# [END app_yaml]
