# [START app_yaml]
env: flex
runtime: nodejs
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)$
    static_files: build/\1
    upload: build/(.*)

# [END app_yaml]