name: Node.js CI/CD

on: 
  push:
  pull_request:

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        include:
          - node-version: 12.x
            deploy: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy to Google App Engine Staging
      if: matrix.deploy && github.ref == 'refs/heads/staging'
      uses: etereo-io/deploy-gae-action@v2.0.3
      with:
        service_account:  ${{ secrets.STAGING_SERVICE_ACCOUNT }}
        project_id: ${{ secrets.STAGING_PROJECT_ID }}
        gae_config_path: './app.yaml'